services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./Database/datasets/:/datasets
      - ./Database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data

  api:
    image: reatanal-api
    build: ./RetAnal/.
    volumes:
      - db-data:/var/lib/postgresql/data
    depends_on:
      - database

  app:
    image: retanal-app
    build: ./RetAnal/RetAnal.App/.
    volumes:
      - ./RetAnal/RetAnal.App/nginx.conf:/etc/nginx/nginx.conf
  
  web:
    image: nginx:alpine
    ports:
      - 7777:8080
    volumes:
      - ./Web/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:
    name: "retanal-data"
